import { db, auth } from "./firebase-config.js";
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-auth.js";
import { ref, get, push, update, remove } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-database.js";
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));let role="";let students={},content={},quizzes={},results={},notifications={};
function toast(t){const x=$("toast");x.textContent=t;x.classList.remove("hide");setTimeout(()=>x.classList.add("hide"),3000)}
async function load(){const [a,b,c,d,e]=await Promise.all([get(ref(db,"students")),get(ref(db,"content")),get(ref(db,"quizzes")),role==="primary"?get(ref(db,"quiz_results")):Promise.resolve({val:()=>({})}),role==="primary"?get(ref(db,"notifications")):Promise.resolve({val:()=>({})})]);students=a.val()||{};content=b.val()||{};quizzes=c.val()||{};results=d.val()||{};notifications=e.val()||{};renderAll()}
function renderAll(){const arr=Object.values(students);$("mStudents").textContent=arr.length;$("mPending").textContent=arr.filter(x=>x.status==="pending").length;$("mContent").textContent=Object.keys(content).length;$("mQuizzes").textContent=Object.keys(quizzes).length;$("recentStudents").innerHTML=role==="primary"?arr.slice().reverse().slice(0,8).map(s=>`<div class="list-item"><div><b>${esc(s.name)}</b><div class="meta">${esc(s.grade)} • ${esc(s.phone)}</div></div><span class="badge ${s.status==="approved"?"success":s.status==="pending"?"warn":"danger"}">${esc(s.status)}</span></div>`).join(""):`<div class="empty-state">Backup Admin مخصص لإدارة المحتوى والاختبارات فقط.</div>`;renderStudents();renderContent();renderQuizzes();if(role==="primary"){renderResults();renderNotifications()}}
function renderStudents(){if(role!=="primary")return;const q=($('studentSearch').value||'').toLowerCase(),f=$('statusFilter').value;const rows=Object.entries(students).filter(([id,s])=>(f==='all'||s.status===f)&&(!q||String(s.name).toLowerCase().includes(q)||String(s.phone).includes(q)));$('studentsTable').innerHTML=`<table class="data-table"><thead><tr><th>الاسم</th><th>الهاتف</th><th>الفرقة</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>${rows.map(([id,s])=>`<tr><td>${esc(s.name)}</td><td>${esc(s.phone)}</td><td>${esc(s.grade)}</td><td><span class="badge ${s.status==='approved'?'success':s.status==='pending'?'warn':'danger'}">${esc(s.status)}</span></td><td>${s.status==='pending'?`<button class="btn btn-small primary-button" data-approve="${id}">قبول</button> <button class="btn btn-small danger-button" data-reject="${id}">رفض</button>`:''}</td></tr>`).join('')}</tbody></table>`}
function renderContent(){$('adminContentList').innerHTML=Object.entries(content).reverse().map(([id,x])=>`<div class="list-item"><div><b>${esc(x.title)}</b><div class="meta">${esc(x.grade)} • ${esc(x.type)} • ${x.isFree!==false?'مجاني':'مقيد'}</div></div><div class="card-actions"><a class="btn btn-small" href="${esc(x.url)}" target="_blank">فتح</a><button class="btn btn-small danger-button" data-del-content="${id}">حذف</button></div></div>`).join('')||`<div class="empty-state">لا يوجد محتوى.</div>`}
function renderQuizzes(){$('adminQuizList').innerHTML=Object.entries(quizzes).reverse().map(([id,x])=>`<div class="list-item"><div><b>${esc(x.title)}</b><div class="meta">${esc(x.grade)} • ${x.duration||0} دقيقة • ${x.questions?.length||0} سؤال • ${x.attemptsPerStudent||1} محاولة</div></div><button class="btn btn-small danger-button" data-del-quiz="${id}">حذف</button></div>`).join('')||`<div class="empty-state">لا توجد اختبارات.</div>`}
function renderResults(){$('adminResults').innerHTML=`<table class="data-table"><thead><tr><th>الطالب</th><th>الاختبار</th><th>النتيجة</th><th>النسبة</th></tr></thead><tbody>${Object.values(results).reverse().map(x=>`<tr><td>${esc(x.studentName)}</td><td>${esc(x.quizTitle)}</td><td>${esc(x.score)}/${esc(x.totalMarks)}</td><td>${esc(x.percentage)}%</td></tr>`).join('')}</tbody></table>`}
function renderNotifications(){$('adminNotifications').innerHTML=Object.values(notifications).reverse().map(x=>`<div class="list-item"><div><b>${esc(x.title)}</b><div class="meta">${esc(x.target)} • ${esc(x.body)}</div></div></div>`).join('')||`<div class="empty-state">لا توجد إشعارات.</div>`}
function setupTabs(){document.querySelectorAll('[data-tab]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();document.querySelectorAll('.sidebar [data-tab]').forEach(x=>x.classList.remove('active'));a.classList.add('active');document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));$('tab-'+a.dataset.tab)?.classList.add('active')}))}
function applyRole(){const backup=role==='backup';$('adminRole').textContent=role==='primary'?'Primary Admin':role==='backup'?'Backup Admin':'Unknown';$('sideRole').textContent=$('adminRole').textContent;$('permissionNote').textContent=backup?'صلاحية محدودة: إدارة المحتوى والاختبارات فقط.':'صلاحية كاملة: الطلاب، المحتوى، الاختبارات، النتائج والإشعارات والإعدادات.';document.querySelectorAll('[data-primary-only]').forEach(x=>x.style.display=backup?'none':'flex');if(backup){document.querySelector('[data-tab="content"]').classList.add('active');document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));$('tab-content').classList.add('active')}}
async function init(u){const rs=await get(ref(db,`adminUsers/${u.uid}/role`));role=rs.val();if(!['primary','backup'].includes(role)){await signOut(auth);alert('هذا الحساب ليس حساب إدارة معتمدًا.');location.href='admin-login.html';return}applyRole();setupTabs();if(role==='primary'){$('studentSearch').oninput=renderStudents;$('statusFilter').onchange=renderStudents}load().catch(e=>{console.error(e);toast('تعذر تحميل لوحة الإدارة')})}
document.addEventListener('click',async e=>{try{const ap=e.target.closest('[data-approve]'),re=e.target.closest('[data-reject]'),dc=e.target.closest('[data-del-content]'),dq=e.target.closest('[data-del-quiz]');if(ap||re){if(role!=='primary')return;const id=(ap||re).dataset.approve||(ap||re).dataset.reject;await update(ref(db,`students/${id}`),{status:ap?'approved':'rejected',updatedAt:new Date().toISOString()});toast('تم تحديث حالة الطالب');await load()}else if(dc){await remove(ref(db,`content/${dc.dataset.delContent}`));toast('تم حذف المحتوى');await load()}else if(dq){await remove(ref(db,`quizzes/${dq.dataset.delQuiz}`));toast('تم حذف الاختبار');await load()}}catch(err){console.error(err);toast('تعذر تنفيذ العملية. راجع Firebase Rules.')}});
$('contentForm').onsubmit=async e=>{e.preventDefault();await push(ref(db,'content'),{title:$('contentTitle').value.trim(),type:$('contentType').value,url:$('contentUrl').value.trim(),grade:$('contentGrade').value,isFree:$('contentFree').checked,published:$('contentPublished').checked,status:$('contentPublished').checked?'published':'hidden',createdAt:new Date().toISOString(),createdBy:auth.currentUser.uid});e.target.reset();$('contentFree').checked=true;$('contentPublished').checked=true;toast('تم حفظ المحتوى');await load()};
$('quizForm').onsubmit=async e=>{e.preventDefault();const qs=$('quizQuestions').value.split('\n').map(x=>x.trim()).filter(Boolean).map(line=>{const p=line.split('|').map(x=>x.trim());return{title:p[0],options:p.slice(1,5),correctIndex:Math.max(0,Math.min(3,Number(p[5]||1)-1))}});if(!qs.length)throw new Error('no questions');await push(ref(db,'quizzes'),{title:$('quizTitle').value.trim(),grade:$('quizGrade').value,duration:Number($('quizDuration').value),attemptsPerStudent:Number($('quizAttempts').value),passPercentage:Number($('quizPass').value),studentLimit:Number($('quizStudentLimit').value)||0,startAt:$('quizStart').value?new Date($('quizStart').value).toISOString():null,endAt:$('quizEnd').value?new Date($('quizEnd').value).toISOString():null,isFree:$('quizFree').checked,randomQuestions:$('quizRandomQuestions').checked,randomOptions:$('quizRandomOptions').checked,showResultImmediately:$('quizShowResult').checked,status:'open',questions:qs,totalScore:qs.length,createdAt:new Date().toISOString(),createdBy:auth.currentUser.uid});e.target.reset();$('quizFree').checked=true;$('quizShowResult').checked=true;toast('تم إنشاء الاختبار');await load()};
$('notificationForm').onsubmit=async e=>{e.preventDefault();if(role!=='primary')return;await push(ref(db,'notifications'),{title:$('notificationTitle').value.trim(),body:$('notificationBody').value.trim(),target:$('notificationTarget').value,createdAt:new Date().toISOString(),createdBy:auth.currentUser.uid});e.target.reset();toast('تم نشر الإشعار');await load()};
$('logoutBtn').onclick=async()=>{await signOut(auth);location.href='admin-login.html'};$('themeToggle').onclick=()=>{document.body.classList.toggle('light');localStorage.setItem('theme',document.body.classList.contains('light')?'light':'dark')};if(localStorage.getItem('theme')==='light')document.body.classList.add('light');onAuthStateChanged(auth,u=>{if(!u){location.href='admin-login.html';return}init(u)});
