import { db, auth } from "./firebase-config.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-auth.js";
import { ref,get,push } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-database.js";
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));const sid=sessionStorage.getItem('studentId'),qid=new URLSearchParams(location.search).get('id');let student,quiz,questions=[],seconds=0,timer;
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
async function start(){if(!sid||!qid){location.href='student.html';return}const [s,q]=await Promise.all([get(ref(db,`students/${sid}`)),get(ref(db,`quizzes/${qid}`))]);student=s.val();quiz=q.val();if(!student||student.status!=='approved'||!quiz){location.href='student.html';return}if(quiz.grade!=='الجميع'&&quiz.grade!==student.grade){alert('هذا الاختبار غير مخصص لفرقتك.');location.href='student.html';return}const now=Date.now();if(quiz.startAt&&now<new Date(quiz.startAt).getTime()||quiz.endAt&&now>new Date(quiz.endAt).getTime()||quiz.status==='closed'){alert('الاختبار غير متاح الآن.');location.href='student.html';return}questions=Array.isArray(quiz.questions)?quiz.questions:Object.values(quiz.questions||{});if(quiz.randomQuestions)questions=shuffle(questions);questions=questions.map(q=>({...q,options:quiz.randomOptions?shuffle(q.options||[]):q.options||[]}));seconds=Math.max(1,Number(quiz.duration||30))*60;$('quizTitle').textContent=quiz.title||'اختبار';$('quizMeta').textContent=`${questions.length} سؤال • ${quiz.duration||0} دقيقة • النجاح ${quiz.passPercentage??50}%`;$('questionCount').textContent=`0 / ${questions.length}`;render();timer=setInterval(()=>{seconds--;tick();if(seconds<=0){clearInterval(timer);submit(true)}},1000);tick()}
function render(){$('quizForm').innerHTML=questions.map((q,i)=>`<article class="question-card"><b>${i+1}. ${esc(q.title)}</b>${(q.options||[]).map((o,j)=>`<label class="option"><input type="radio" name="q${i}" value="${j}"><span>${esc(o)}</span></label>`).join('')}</article>`).join('')}
function tick(){const m=Math.floor(seconds/60),s=seconds%60;$('timer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;const answered=document.querySelectorAll('input[type=radio]:checked').length;$('questionCount').textContent=`${answered} / ${questions.length}`;$('quizProgress').firstElementChild.style.width=`${Math.round(answered/questions.length*100)}%`;if(seconds<=30)$('timer').classList.add('danger-button')}
async function submit(auto=false){$('submitQuiz').disabled=true;if(timer)clearInterval(timer);let score=0,answered=0;questions.forEach((q,i)=>{const selected=document.querySelector(`input[name=q${i}]:checked`);if(selected){answered++;if(Number(selected.value)===Number(q.correctIndex))score++}});const total=questions.length,percentage=total?Math.round(score/total*100):0,passed=percentage>=Number(quiz.passPercentage??50);const result={studentId:sid,studentName:student.name,studentGrade:student.grade,quizId:qid,quizTitle:quiz.title,score,totalMarks:total,rawScore:score,percentage,passed,submittedAt:new Date().toISOString(),autoSubmitted:auto};await push(ref(db,`quiz_results/${sid}`),result);$('quizState').style.display='none';$('quizResult').style.display='block';$('quizResult').innerHTML=`<div class="tag">RESULT</div><h2>${passed?'أحسنت!':'تم تسجيل النتيجة'}</h2><div class="kpi">${percentage}%</div><p class="muted">${score} من ${total} إجابة صحيحة • ${passed?'ناجح':'لم يصل لنسبة النجاح'}</p><a class="btn primary-button" href="student.html">العودة للوحة الطالب</a>`}
$('submitQuiz').onclick=()=>submit(false);$('leaveQuiz').onclick=()=>{if(confirm('الخروج سيغلق الاختبار الحالي.'))location.href='student.html'};onAuthStateChanged(auth,u=>{if(!u||u.uid!==`student_${sid}`)location.href='login.html';else start().catch(e=>{console.error(e);alert('تعذر فتح الاختبار');location.href='student.html'})});
