import { db, auth } from "./firebase-config.js";
import { onAuthStateChanged, signOut } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-auth.js";
import { ref, get, update, push } from "https://www.gstatic.com/firebasejs/12.4.0/firebase-database.js";
const $=id=>document.getElementById(id),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const sid=sessionStorage.getItem("studentId");if(!sid)location.href="login.html";
function toast(t){const x=$("toast");x.textContent=t;x.classList.remove("hide");setTimeout(()=>x.classList.add("hide"),2800)}
function isAvailable(q){const now=Date.now();if(q.startAt&&now<new Date(q.startAt).getTime())return false;if(q.endAt&&now>new Date(q.endAt).getTime())return false;return q.status!=="closed"}
async function load(){
 const [sSnap,cSnap,qSnap,rSnap,nSnap]=await Promise.all([get(ref(db,`students/${sid}`)),get(ref(db,"content")),get(ref(db,"quizzes")),get(ref(db,`quiz_results/${sid}`)),get(ref(db,"notifications"))]);
 const s=sSnap.val();if(!s||s.status!=="approved"){await signOut(auth);sessionStorage.clear();location.href="login.html";return}
 $("studentName").textContent=s.name||"طالب";$("headingName").textContent=s.name||"يا طالب";$("studentGrade").textContent=s.grade||"";$("profileName").textContent=s.name||"—";$("profilePhone").textContent=s.phone||"—";$("profileGrade").textContent=s.grade||"—";$("profileStatus").textContent=s.status||"—";
 const content=Object.entries(cSnap.val()||{}).map(([id,x])=>({id,...x})).filter(x=>x.status!=="hidden"&&x.published!==false&&(x.grade==="الجميع"||x.grade===s.grade));
 const quizzes=Object.entries(qSnap.val()||{}).map(([id,x])=>({id,...x})).filter(x=>(x.grade==="الجميع"||x.grade===s.grade)&&isAvailable(x));
 const results=Object.values(rSnap.val()||{});const notes=Object.values(nSnap.val()||{}).filter(x=>x.target==="الجميع"||x.target===s.grade);
 $("contentCount").textContent=content.length;$("quizCount").textContent=quizzes.length;$("resultCount").textContent=results.length;$("notificationCount").textContent=notes.length;
 const contentCard=x=>`<article class="content-card"><div class="card-title">${esc(x.title)}</div><div class="card-meta">${esc(x.type||"محتوى")} • ${x.isFree!==false?"مجاني":"مقيد"}<br>${esc(x.grade||"الجميع")}</div><div class="card-actions"><a class="btn btn-small primary-button" href="${esc(x.url)}" target="_blank" rel="noopener">فتح المحتوى ↗</a></div></article>`;
 $("contentList").innerHTML=content.length?content.slice().reverse().map(contentCard).join(""):`<div class="ui-card empty-state">لا يوجد محتوى منشور حاليًا.</div>`;
 $("overviewContent").innerHTML=content.length?content.slice().reverse().slice(0,4).map(x=>`<div class="list-item"><div><b>${esc(x.title)}</b><div class="meta">${esc(x.type||"محتوى")}</div></div><a class="btn btn-small" href="${esc(x.url)}" target="_blank">فتح</a></div>`).join(""):`<div class="empty-state">لا يوجد محتوى.</div>`;
 $("quizList").innerHTML=quizzes.length?quizzes.slice().reverse().map(x=>`<article class="quiz-card"><div class="card-title">${esc(x.title)}</div><div class="card-meta">${x.duration||0} دقيقة • ${x.questions?.length||0} سؤال • ${x.attemptsPerStudent||1} محاولة • نجاح ${x.passPercentage??50}%</div><div class="card-actions"><a class="btn btn-small primary-button" href="quiz.html?id=${encodeURIComponent(x.id)}">ابدأ الاختبار</a></div></article>`).join(""):`<div class="ui-card empty-state">لا توجد اختبارات متاحة.</div>`;
 $("resultsList").innerHTML=results.length?results.slice().reverse().map(x=>`<article class="result-card"><div class="card-title">${esc(x.quizTitle)}</div><div class="kpi">${esc(x.percentage)}%</div><div class="card-meta">${esc(x.score)} / ${esc(x.totalMarks)} • ${esc(x.passed?"ناجح":"لم ينجح")}</div></article>`).join(""):`<div class="ui-card empty-state">لا توجد نتائج بعد.</div>`;
 $("notificationList").innerHTML=notes.length?notes.slice().reverse().map(x=>`<article class="notification-card"><div class="card-title">${esc(x.title)}</div><div class="card-meta">${esc(x.body)}<br>${esc(x.target)}</div></article>`).join(""):`<div class="ui-card empty-state">لا توجد إشعارات.</div>`;
 $("overviewNotifications").innerHTML=notes.length?notes.slice().reverse().slice(0,4).map(x=>`<div class="list-item"><div><b>${esc(x.title)}</b><div class="meta">${esc(x.body)}</div></div></div>`).join(""):`<div class="empty-state">لا توجد إشعارات.</div>`;
 await update(ref(db,`students/${sid}`),{lastActive:new Date().toISOString()});
}
function setup(){document.querySelectorAll("[data-tab]").forEach(a=>a.addEventListener("click",e=>{e.preventDefault();document.querySelectorAll(".sidebar [data-tab]").forEach(x=>x.classList.remove("active"));a.classList.add("active");document.querySelectorAll(".tab-panel").forEach(x=>x.classList.remove("active"));$("tab-"+a.dataset.tab)?.classList.add("active")}));$("logoutBtn").onclick=async()=>{await signOut(auth);sessionStorage.clear();location.href="login.html"};$("themeToggle").onclick=()=>{document.body.classList.toggle("light");localStorage.setItem("theme",document.body.classList.contains("light")?"light":"dark")};if(localStorage.getItem("theme")==="light")document.body.classList.add("light")}
setup();onAuthStateChanged(auth,u=>{if(!u||u.uid!==`student_${sid}`){location.href="login.html";return}load().catch(e=>{console.error(e);toast("تعذر تحميل البيانات")})});
